name: Build

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
    tags: ["*"]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Build
      run: go build -o dist/src.linux.$(uname -m) src.go

    - name: Store Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Linux build
        path: dist/src.linux.*

  release:
    runs-on: ubuntu-latest
    needs: ["build-linux"]
    permissions:
      contents: write
      actions: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Collect builds
        uses: actions/download-artifact@v4
        with:
          path: dist/
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          draft: ${{ startsWith(github.ref, 'refs/tags/draft-') }}
